/* SETTINGS */
export const CHANGE_LOCALE = "CHANGE_LOCALE";

/* AUTH */
export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const LOGOUT_USER = "LOGOUT_USER";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_SUCCESS = "FORGOT_PASSWORD_SUCCESS";
export const FORGOT_PASSWORD_ERROR = "FORGOT_PASSWORD_ERROR";
export const RESET_PASSWORD = "RESET_PASSWORD";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR";

/* MENU */
export const MENU_SET_CLASSNAMES = "MENU_SET_CLASSNAMES";
export const MENU_CONTAINER_ADD_CLASSNAME = "MENU_CONTAINER_ADD_CLASSNAME";
export const MENU_CLICK_MOBILE_MENU = "MENU_CLICK_MOBILE_MENU";
export const MENU_CHANGE_DEFAULT_CLASSES = "MENU_CHANGE_DEFAULT_CLASSES";
export const MENU_CHANGE_HAS_SUB_ITEM_STATUS =
  "MENU_CHANGE_HAS_SUB_ITEM_STATUS";

/* TODOAPP*/
export const TODO_GET_LIST = "TODO_GET_LIST";
export const TODO_GET_LIST_SUCCESS = "TODO_GET_LIST_SUCCESS";
export const TODO_GET_LIST_ERROR = "TODO_GET_LIST_ERROR";
export const TODO_GET_LIST_WITH_FILTER = "TODO_GET_LIST_WITH_FILTER";
export const TODO_GET_LIST_WITH_ORDER = "TODO_GET_LIST_WITH_ORDER";
export const TODO_GET_LIST_SEARCH = "TODO_GET_LIST_SEARCH";
export const TODO_ADD_ITEM = "TODO_ADD_ITEM";
export const TODO_ADD_ITEM_SUCCESS = "TODO_ADD_ITEM_SUCCESS";
export const TODO_ADD_ITEM_ERROR = "TODO_ADD_ITEM_ERROR";
export const TODO_SELECTED_ITEMS_CHANGE = "TODO_SELECTED_ITEMS_CHANGE";

/* CHAT APP*/
export const CHAT_GET_CONTACTS = "CHAT_GET_CONTACTS";
export const CHAT_GET_CONTACTS_SUCCESS = "CHAT_GET_CONTACTS_SUCCESS";
export const CHAT_GET_CONTACTS_ERROR = "CHAT_GET_CONTACTS_ERROR";
export const CHAT_GET_CONVERSATIONS = "CHAT_GET_CONVERSATIONS";
export const CHAT_GET_CONVERSATIONS_SUCCESS = "CHAT_GET_CONVERSATIONS_SUCCESS";
export const CHAT_GET_CONVERSATIONS_ERROR = "CHAT_GET_CONVERSATIONS_ERROR";
export const CHAT_ADD_MESSAGE_TO_CONVERSATION =
  "CHAT_ADD_MESSAGE_TO_CONVERSATION";
export const CHAT_CREATE_CONVERSATION = "CHAT_CREATE_CONVERSATION";
export const CHAT_SEARCH_CONTACT = "CHAT_SEARCH_CONTACT";
export const CHAT_CHANGE_CONVERSATION = "CHAT_CHANGE_CONVERSATION";

/* SURVEY LIST APP*/
export const SURVEY_LIST_GET_LIST = "SURVEY_LIST_GET_LIST";
export const SURVEY_LIST_GET_LIST_SUCCESS = "SURVEY_LIST_GET_LIST_SUCCESS";
export const SURVEY_LIST_GET_LIST_ERROR = "SURVEY_LIST_GET_LIST_ERROR";
export const SURVEY_LIST_GET_LIST_WITH_FILTER =
  "SURVEY_LIST_GET_LIST_WITH_FILTER";
export const SURVEY_LIST_GET_LIST_WITH_ORDER =
  "SURVEY_LIST_GET_LIST_WITH_ORDER";
export const SURVEY_LIST_GET_LIST_SEARCH = "SURVEY_LIST_GET_LIST_SEARCH";
export const SURVEY_LIST_ADD_ITEM = "SURVEY_LIST_ADD_ITEM";
export const SURVEY_LIST_ADD_ITEM_SUCCESS = "SURVEY_LIST_ADD_ITEM_SUCCESS";
export const SURVEY_LIST_ADD_ITEM_ERROR = "SURVEY_LIST_ADD_ITEM_ERROR";
export const SURVEY_LIST_SELECTED_ITEMS_CHANGE =
  "SURVEY_LIST_SELECTED_ITEMS_CHANGE";

/* SURVEY DETAIL APP*/
export const SURVEY_GET_DETAILS = "SURVEY_GET_DETAILS";
export const SURVEY_GET_DETAILS_SUCCESS = "SURVEY_GET_DETAILS_SUCCESS";
export const SURVEY_GET_DETAILS_ERROR = "SURVEY_GET_DETAILS_ERROR";
export const SURVEY_DELETE_QUESTION = "SURVEY_DELETE_QUESTION";
export const SURVEY_SAVE = "SURVEY_SAVE";

// GET,ADD, EDIT, DELETE GENRE
export const GET_GENRE = "GET_GENRE";
export const ADD_GENRE = "ADD_GENRE";
export const EDIT_GENRE = "EDIT_GENRE";
export const DELETE_GENRE = "DELETE_GENRE";
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS";
export const GET_GENRE_ERROR = "GET_GENRE_ERROR";
export const ADD_GENRE_SUCCESS = "ADD_GENRE_SUCCESS";
export const ADD_GENRE_ERROR = "ADD_GENRE_ERROR";
export const EDIT_GENRE_SUCCESS = "EDIT_GENRE_SUCCESS";
export const EDIT_GENRE_ERROR = "EDIT_GENRE_ERROR";
export const DELETE_GENRE_SUCCESS = "DELETE_GENRE_SUCCESS";
export const DELETE_GENRE_ERROR = "DELETE_GENRE_ERROR";
export const DELETE_GENRE_QUESTION = "DELETE_GENRE_QUESTION";

//GET,ADD, EDIT, DELETE ACTOR
export const GET_ACTOR = "GET_ACTOR";
export const ADD_ACTOR = "ADD_ACTOR";
export const EDIT_ACTOR = "EDIT_ACTOR";
export const DELETE_ACTOR = "DELETE_ACTOR";
export const GET_ACTOR_SUCCESS = "GET_ACTOR_SUCCESS";
export const GET_ACTOR_ERROR = "GET_ACTOR_ERROR";
export const ADD_ACTOR_SUCCESS = "ADD_ACTOR_SUCCESS";
export const ADD_ACTOR_ERROR = "ADD_ACTOR_ERROR";
export const EDIT_ACTOR_SUCCESS = "EDIT_ACTOR_SUCCESS";
export const EDIT_ACTOR_ERROR = "EDIT_ACTOR_ERROR";
export const DELETE_ACTOR_SUCCESS = "DELETE_ACTOR_SUCCESS";
export const DELETE_ACTOR_ERROR = "DELETE_ACTOR_ERROR";
export const DELETE_ACTOR_QUESTION = "DELETE_ACTOR_QUESTION";

//GET,ADD, EDIT, DELETE MOVIE
export const GET_MOVIE = "GET_MOVIE";
export const GET_MOVIE_ID = "GET_MOVIE_ID";
export const ADD_MOVIE = "ADD_MOVIE";
export const EDIT_MOVIE = "EDIT_MOVIE";
export const DELETE_MOVIE = "DELETE_MOVIE";
export const GET_MOVIE_SUCCESS = "GET_MOVIE_SUCCESS";
export const GET_MOVIE_ERROR = "GET_MOVIE_ERROR";
export const GET_MOVIE_ID_SUCCESS = "GET_MOVIE_ID_SUCCESS";
export const GET_MOVIE_ID_ERROR = "GET_MOVIE_ID_ERROR";
export const ADD_MOVIE_SUCCESS = "ADD_MOVIE_SUCCESS";
export const ADD_MOVIE_ERROR = "ADD_MOVIE_ERROR";
export const EDIT_MOVIE_SUCCESS = "EDIT_MOVIE_SUCCESS";
export const EDIT_MOVIE_ERROR = "EDIT_MOVIE_ERROR";
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS";
export const DELETE_MOVIE_ERROR = "DELETE_MOVIE_ERROR";
export const DELETE_MOVIE_QUESTION = "DELETE_MOVIE_QUESTION";

//GET, DELETE COMMENT
export const GET_COMMENT = "GET_COMMENT";
export const GET_COMMENT_SUCCESS = "GET_COMMENT_SUCCESS";
export const GET_COMMENT_ERROR = "GET_COMMENT_ERROR";
export const DELETE_COMMENT = "DELETE_COMMENT";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";
export const DELETE_COMMENT_MANY = "DELETE_COMMENT_MANY";

//GET, DELETE REVIEW
export const GET_REVIEW = "GET_REVIEW";
export const ADD_REVIEW = "ADD_REVIEW";
export const GET_REVIEW_SUCCESS = "GET_REVIEW_SUCCESS";
export const GET_REVIEW_ERROR = "GET_REVIEW_ERROR";
export const ADD_REVIEW_SUCCESS = "ADD_REVIEW_SUCCESS";
export const ADD_REVIEW_ERROR = "ADD_REVIEW_ERROR";
export const DELETE_REVIEW = "DELETE_REVIEW";
export const DELETE_REVIEW_SUCCESS = "DELETE_REVIEW_SUCCESS";
export const DELETE_REVIEW_ERROR = "DELETE_REVIEW_ERROR";
export const DELETE_REVIEW_MANY = "DELETE_REVIEW_MANY";

//GET,ADD, EDIT, DELETE EPISODE
export const GET_EPISODE = "GET_EPISODE";
export const GET_EPISODE_ID = "GET_EPISODE_ID";
export const ADD_EPISODE = "ADD_EPISODE";
export const EDIT_EPISODE = "EDIT_EPISODE";
export const DELETE_EPISODE = "DELETE_EPISODE";
export const GET_EPISODE_SUCCESS = "GET_EPISODE_SUCCESS";
export const GET_EPISODE_ERROR = "GET_EPISODE_ERROR";
export const GET_EPISODE_ID_SUCCESS = "GET_EPISODE_ID_SUCCESS";
export const GET_EPISODE_ID_ERROR = "GET_EPISODE_ID_ERROR";
export const ADD_EPISODE_SUCCESS = "ADD_EPISODE_SUCCESS";
export const ADD_EPISODE_ERROR = "ADD_EPISODE_ERROR";
export const EDIT_EPISODE_SUCCESS = "EDIT_EPISODE_SUCCESS";
export const EDIT_EPISODE_ERROR = "EDIT_EPISODE_ERROR";
export const DELETE_EPISODE_SUCCESS = "DELETE_EPISODE_SUCCESS";
export const DELETE_EPISODE_ERROR = "DELETE_EPISODE_ERROR";
export const DELETE_EPISODE_QUESTION = "DELETE_EPISODE_QUESTION";

//GET,ADD, EDIT, DELETE LINK
export const GET_LINK = "GET_LINK";
export const GET_LINK_ID = "GET_LINK_ID";
export const ADD_LINK = "ADD_LINK";
export const EDIT_LINK = "EDIT_LINK";
export const DELETE_LINK = "DELETE_LINK";
export const GET_LINK_SUCCESS = "GET_LINK_SUCCESS";
export const GET_LINK_ERROR = "GET_LINK_ERROR";
export const GET_LINK_ID_SUCCESS = "GET_LINK_ID_SUCCESS";
export const GET_LINK_ID_ERROR = "GET_LINK_ID_ERROR";
export const ADD_LINK_SUCCESS = "ADD_LINK_SUCCESS";
export const ADD_LINK_ERROR = "ADD_LINK_ERROR";
export const EDIT_LINK_SUCCESS = "EDIT_LINK_SUCCESS";
export const EDIT_LINK_ERROR = "EDIT_LINK_ERROR";
export const DELETE_LINK_SUCCESS = "DELETE_LINK_SUCCESS";
export const DELETE_LINK_ERROR = "DELETE_LINK_ERROR";
export const DELETE_LINK_QUESTION = "DELETE_LINK_QUESTION";

// GET, EDIT USER
export const GET_USER = "GET_USER";
export const GET_FAVORITE_LIST_BY_USER_ID = "GET_FAVORITE_LIST_BY_USER_ID";
export const EDIT_USER = "EDIT_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_ERROR = "GET_USER_ERROR";
export const GET_FAVORITE_LIST_BY_USER_ID_SUCCESS = "GET_FAVORITE_LIST_BY_USER_ID_SUCCESS";
export const GET_FAVORITE_LIST_BY_USER_ID_ERROR = "GET_FAVORITE_LIST_BY_USER_ID_ERROR";
export const EDIT_USER_SUCCESS = "EDIT_USER_SUCCESS";
export const EDIT_USER_ERROR = "EDIT_USER_ERROR";
export const DELETE_USER = "DELETE_USER";
export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USER_ERROR = "DELETE_USER_ERROR";
export const DELETE_USER_QUESTION = "DELETE_USER_QUESTION";

export * from "./menu/actions";
export * from "./settings/actions";
export * from "./auth/actions";
export * from "./todo/actions";
export * from "./genre/actions";
export * from "./actor/actions";
export * from "./movie/actions";
export * from "./comment/actions";
export * from "./review/actions";
export * from "./episode/actions";
export * from "./user/actions";
export * from "./surveyDetail/actions";